(cl:defpackage campus-srv
  (:use )
  (:export
   "NAVIGATIONREQUEST"
   "<NAVIGATIONREQUEST-REQUEST>"
   "NAVIGATIONREQUEST-REQUEST"
   "<NAVIGATIONREQUEST-RESPONSE>"
   "NAVIGATIONREQUEST-RESPONSE"
  ))

